### ISSUE TITLE
Master branch build error using GCC v10.2 [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [gwatcha/myrisa-modules#1]
In file included from src/Frame.cpp:1:
src/Frame.hpp:45:11: error: flexible array member 'myrisa::Frame::Engine::layers' in an otherwise empty 'struct myrisa::Frame::Engine'
   45 |    Layer* layers[]{};
      |           ^~~~~~
src/Frame.hpp:67:7: error: virtual function 'virtual int myrisa::Frame::channels()' overriding final function
   67 |   int channels() override;
      |       ^~~~~~~~
In file included from src/Frame_IO.hpp:4,
                 from src/Frame.hpp:3,
                 from src/Frame.cpp:1:
src/expanders.hpp:98:6: note: overridden function is 'int myrisa::ExpanderModule<MSG, BASE>::channels() [with MSG = myrisa::SignalExpanderMessage; BASE = myrisa::MyrisaModule]'
   98 |  int channels() override final {
      |      ^~~~~~~~
In file included from src/Frame.cpp:1:
src/Frame.hpp:45:11: error: initializer for flexible array member 'myrisa::Frame::Engine::Layer* myrisa::Frame::Engine::layers []'
   45 |    Layer* layers[]{};
      |           ^~~~~~
In file included from src/myrisa.cpp:3:
src/Frame.hpp:45:11: error: flexible array member 'myrisa::Frame::Engine::layers' in an otherwise empty 'struct myrisa::Frame::Engine'
   45 |    Layer* layers[]{};
      |           ^~~~~~
src/Frame.hpp:67:7: error: virtual function 'virtual int myrisa::Frame::channels()' overriding final function
   67 |   int channels() override;
      |       ^~~~~~~~
In file included from src/Frame_IO.hpp:4,
                 from src/Frame.hpp:3,
                 from src/myrisa.cpp:3:
src/expanders.hpp:98:6: note: overridden function is 'int myrisa::ExpanderModule<MSG, BASE>::channels() [with MSG = myrisa::SignalExpanderMessage; BASE = myrisa::MyrisaModule]'
   98 |  int channels() override final {
      |      ^~~~~~~~
In file included from src/myrisa.cpp:3:
src/Frame.hpp:45:11: error: initializer for flexible array member 'myrisa::Frame::Engine::Layer* myrisa::Frame::Engine::layers []'
   45 |    Layer* layers[]{};
      |           ^~~~~~
make: *** [../../compile.mk:69: build/src/myrisa.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [../../compile.mk:69: build/src/Frame.cpp.o] Error 1

**Comment by gwatcha** [comment]
Oh wow, thanks for helping out! Could you try out the build now? Note that I just started this repo so most functionality is not working yet and it is constantly changing, so helping out may be difficult.

Also I happen to be taking a dsp course right now in University, and it so happened that the final is replaced with a project of one's choice, so I decided to work on this project for it. I will have to ask the professor if she allows people contributing, so before then, please hold off on any commits! (I don't want to fail! haha)

**Comment by SteveRussell33** [comment]
OK that's better. Now has just a couple of GCC warnings about the use of integers, which I'll let you sort out.

src/Frame.cpp: In member function 'virtual void myrisa::Frame::processChannel(const rack::engine::Module::ProcessArgs&, int)':
src/Frame.cpp:63:44: warning: format '%d' expects argument of type 'int', but argument 4 has type 'std::vector<myrisa::Frame::Engine::Scene::Layer*>::size_type' {aka 'long long unsigned int'} [-Wformat=]
   63 |         printf("disengages: %d %d #layer: %d rec_lery: %d\n", recording_length,
      |                                           ~^
      |                                            |
      |                                            int
      |                                           %lld
   64 |                rec_scene->scene_length, rec_scene->layers.size(),
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                               |
      |                                                               std::vector<myrisa::Frame::Engine::Scene::Layer*>::size_type {aka long long unsigned int}
src/Frame.cpp:90:53: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
   90 |     if (active_scene->mode != Mode::READ && layer_i == active_scene->current_layer) {
      |                                             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by SteveRussell33** [comment]
Just to let you know "frame" and "f-x" modules crash. I'll come back later [got to go out] and edit this post with a log (hopefully) using my debug build of Rack and GDB.

**Comment by gwatcha** [comment]
Right now, the only functionality is having a "signal" module to the left of a "frame" module, and being able to twist the delta knob to the right to add recordings to a scene. It's very early development right now!

**Comment by gwatcha** [comment]
It's strange how the frame module crashes for you however, it is working for me. It might have to do with different operating systems, but whatever the reason, thanks for telling me.

**Comment by gwatcha** [comment]
Okay nevvermind, frame crashes for me as well, i'll look into it

**Comment by SteveRussell33** [comment]
This is a log of a crash after selecting the frame module from Rack's browser.
```
Thread 15 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 6364.0x1fa0]
0x0000000012932445 in myrisa::Frame::processChannel (this=0x1c1748b0, args=..., c=0) at src/Frame.cpp:295
295       e.step(next_in);
(gdb) bt
#0  0x0000000012932445 in myrisa::Frame::processChannel (this=0x1c1748b0, args=..., c=0) at src/Frame.cpp:295
#1  0x00000000129328b7 in myrisa::MyrisaModule::process (this=0x1c1748b0, args=...) at src/module.cpp:53
#2  0x000000001294096d in myrisa::ExpanderModule<myrisa::SignalExpanderMessage, myrisa::MyrisaModule>::process (this=0x1c1748b0, args=...) at src/expanders.hpp:106
#3  0x000000000049f347 in rack::engine::Engine_stepModules (threadId=0, that=<optimized out>, that=<optimized out>) at src/engine/Engine.cpp:269
#4  0x00000000004a1652 in rack::engine::Engine_step (that=0xd1446d0) at src/engine/Engine.cpp:346
#5  rack::engine::Engine_run (that=0xd1446d0) at src/engine/Engine.cpp:448
#6  operator() (__closure=<optimized out>) at src/engine/Engine.cpp:482
#7  std::__invoke_impl<void, rack::engine::Engine::start()::<lambda()> > (__f=...) at C:/msys64/mingw64/include/c++/10.2.0/bits/invoke.h:60
#8  std::__invoke<rack::engine::Engine::start()::<lambda()> > (__fn=...) at C:/msys64/mingw64/include/c++/10.2.0/bits/invoke.h:95
#9  std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > >::_M_invoke<0> (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/10.2.0/thread:264
#10 std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > >::operator() (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/10.2.0/thread:271
#11 std::thread::_State_impl<std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > > >::_M_run(void) (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/10.2.0/thread:215
#12 0x000000006fd39d01 in ?? () from /c/Program Files/VCV/v1/libstdc++-6.dll
#13 0x0000000064944b42 in ?? () from /c/Program Files/VCV/v1/libwinpthread-1.dll
#14 0x00007fff99acb04a in msvcrt!_beginthreadex () from /c/WINDOWS/System32/msvcrt.dll
#15 0x00007fff99acb11c in msvcrt!_endthreadex () from /c/WINDOWS/System32/msvcrt.dll
#16 0x00007fff99487c24 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#17 0x00007fff9b00cea1 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#18 0x0000000000000000 in ?? ()
```

**Comment by SteveRussell33** [comment]
This is the log from f-x crashing Rack
```


Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000000497e8a in rack::app::RackWidget_updateAdjacent (that=<optimized out>, that=<optimized out>) at src/app/RackWidget.cpp:342
342                     mw->module->leftExpander.moduleId = mwLeft ? mwLeft->module->id : -1;
(gdb) bt
#0  0x0000000000497e8a in rack::app::RackWidget_updateAdjacent (that=<optimized out>, that=<optimized out>) at src/app/RackWidget.cpp:342
#1  0x0000000000490c52 in rack::app::chooseModel (model=<optimized out>) at src/app/ModuleBrowser.cpp:88
#2  0x000000000076259c in rack::app::ModelBox::onButton (e=..., this=0x20c751b0) at src/app/ModuleBrowser.cpp:220
#3  rack::app::ModelBox::onButton (this=0x20c751b0, e=...) at src/app/ModuleBrowser.cpp:214
#4  0x000000000077849b in rack::widget::Widget::recursePositionEvent<void (rack::widget::Widget::*)(rack::event::Button const&), rack::event::Button> (e=...,
    f=&virtual table offset 72, this=0x20bce900) at include/math.hpp:196
#5  rack::widget::Widget::onButton (this=0x20bce900, e=...) at include/widget/Widget.hpp:150
#6  0x000000000077849b in rack::widget::Widget::recursePositionEvent<void (rack::widget::Widget::*)(rack::event::Button const&), rack::event::Button> (e=...,
    f=&virtual table offset 72, this=0x20bbd840) at include/math.hpp:196
#7  rack::widget::Widget::onButton (this=0x20bbd840, e=...) at include/widget/Widget.hpp:150
#8  0x000000000077849b in rack::widget::Widget::recursePositionEvent<void (rack::widget::Widget::*)(rack::event::Button const&), rack::event::Button> (e=...,
    f=&virtual table offset 72, this=0xd18cb20) at include/math.hpp:196
#9  rack::widget::Widget::onButton (this=0xd18cb20, e=...) at include/widget/Widget.hpp:150
#10 0x00000000004a8194 in rack::widget::Widget::recursePositionEvent<void (rack::widget::Widget::*)(rack::event::Button const&), rack::event::Button> (e=...,
    f=&virtual table offset 72, this=0x20bb5310) at include/math.hpp:196
#11 rack::widget::Widget::onButton (e=..., this=0x20bb5310) at include/widget/Widget.hpp:150
#12 rack::ui::ScrollWidget::onButton (this=0x20bb5310, e=...) at src/ui/ScrollWidget.cpp:67
#13 0x0000000000777798 in rack::widget::Widget::recursePositionEvent<void (rack::widget::Widget::*)(rack::event::Button const&), rack::event::Button> (e=...,
    f=&virtual table offset 72, this=0xd185540) at include/math.hpp:196
#14 rack::widget::Widget::onButton (e=..., this=0xd185540) at include/widget/Widget.hpp:150
#15 rack::widget::OpaqueWidget::onButton (this=0xd185540, e=...) at include/widget/OpaqueWidget.hpp:21
#16 0x0000000000758bc7 in rack::widget::Widget::recursePositionEvent<void (rack::widget::Widget::*)(rack::event::Button const&), rack::event::Button> (e=...,
    f=&virtual table offset 72, this=0xd1854d0) at include/math.hpp:196
#17 rack::widget::Widget::onButton (e=..., this=0xd1854d0) at include/widget/Widget.hpp:150
#18 rack::widget::OpaqueWidget::onButton (e=..., this=0xd1854d0) at include/widget/OpaqueWidget.hpp:21
#19 rack::app::BrowserOverlay::onButton (this=0xd1854d0, e=...) at src/app/ModuleBrowser.cpp:123
#20 0x0000000000777798 in rack::widget::Widget::recursePositionEvent<void (rack::widget::Widget::*)(rack::event::Button const&), rack::event::Button> (e=...,
    f=&virtual table offset 72, this=0xd183220) at include/math.hpp:196
#21 rack::widget::Widget::onButton (e=..., this=0xd183220) at include/widget/Widget.hpp:150
#22 rack::widget::OpaqueWidget::onButton (this=0xd183220, e=...) at include/widget/OpaqueWidget.hpp:21
#23 0x0000000000476586 in rack::event::State::handleButton (this=0xd063dc0, pos=..., button=0, action=1, mods=32)
    at C:/msys64/mingw64/include/c++/10.2.0/bits/stl_iterator.h:167
#24 0x0000000000489110 in rack::mouseButtonCallback (win=<optimized out>, button=0, action=1, mods=32) at src/window.cpp:123
#25 0x00000000004dbbce in windowProc (hWnd=0xb0424, uMsg=513, wParam=<optimized out>, lParam=<optimized out>)
    at C:/_Projects/VCVRack/V1/Rack/dep/glfw/src/win32_window.c:809
#26 0x00007fff9a185c1d in USER32!CallWindowProcW () from /c/WINDOWS/System32/USER32.dll
#27 0x00007fff9a1858ee in USER32!CallWindowProcW () from /c/WINDOWS/System32/USER32.dll
#28 0x00007fff792e3919 in glPushClientAttrib () from /c/WINDOWS/SYSTEM32/OPENGL32.dll
#29 0x00007fff9a185c1d in USER32!CallWindowProcW () from /c/WINDOWS/System32/USER32.dll
#30 0x00007fff9a185612 in USER32!DispatchMessageW () from /c/WINDOWS/System32/USER32.dll
#31 0x00000000004de0be in _glfwPlatformPollEvents () at C:/_Projects/VCVRack/V1/Rack/dep/glfw/src/win32_window.c:1923
#32 0x00000000004d73da in glfwPollEvents () at C:/_Projects/VCVRack/V1/Rack/dep/glfw/src/window.c:1072
#33 0x000000000048a1ac in rack::Window::run (this=0xd063eb0) at src/window.cpp:343
#34 0x0000000000786842 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:203
```

**Comment by gwatcha** [comment]
Frame should work now, I haven't figured out Frame-X yet.

**Comment by gwatcha** [comment]
So basically the only thing that you can try out right now is putting a frame next to a signal module and using the delta knob to record loops, and the scene knob to change scenes.
